#!/bin/bash
# Generate Resources/Roar.icns from Resources/icon.svg.
#
# macOS app icons must be `.icns` files; SVG is not a valid bundle
# resource for `CFBundleIconFile`. We keep the SVG as the source of
# truth (versioned, hand-edited) and treat the `.icns` as a built
# artefact regenerated by this script. The .icns IS committed to the
# repo so a fresh clone can `xcodegen && xcodebuild` without needing
# `rsvg-convert` installed — only contributors who edit the SVG
# need this script.
#
# Workflow:
#   1. Rasterise the SVG to PNGs at every size macOS expects in an
#      `.iconset` directory. iconutil's documented mandatory set is:
#      16, 32 (16@2x), 32, 64 (32@2x), 128, 256 (128@2x), 256,
#      512 (256@2x), 512, 1024 (512@2x). Missing sizes downgrade
#      LaunchServices' rendering at the corresponding scale.
#   2. Run `iconutil --convert icns` to package the .iconset into
#      a single `.icns` file.
#   3. Clean up the intermediate .iconset.
#
# Requires `rsvg-convert` (brew install librsvg) and `iconutil`
# (ships with macOS).
#
# Usage:
#   ./scripts/generate-icon.sh
#
# Run from any directory — the script resolves paths relative to
# its own location.

set -euo pipefail

# Resolve repo root from script location so the script works
# regardless of the caller's cwd. `dirname "$0"` is the script's
# parent (`scripts/`); one more `..` is the repo root.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SOURCE_SVG="$REPO_ROOT/Resources/icon.svg"
OUTPUT_ICNS="$REPO_ROOT/Resources/Roar.icns"

# Tool checks. Fail loudly up front instead of producing a partial
# .iconset that the caller would then have to clean up by hand.
if ! command -v rsvg-convert >/dev/null 2>&1; then
    echo "error: rsvg-convert not found. Install with: brew install librsvg" >&2
    exit 1
fi
if ! command -v iconutil >/dev/null 2>&1; then
    echo "error: iconutil not found. Ships with macOS — are you on Linux?" >&2
    exit 1
fi
if [[ ! -f "$SOURCE_SVG" ]]; then
    echo "error: $SOURCE_SVG missing." >&2
    exit 1
fi

# Build the .iconset under a temp directory so a Ctrl+C halfway
# through doesn't leave stale PNGs in the repo. `trap` cleans up
# on any exit path (success, failure, signal).
WORK_DIR="$(mktemp -d -t roar-iconset)"
trap 'rm -rf "$WORK_DIR"' EXIT
ICONSET="$WORK_DIR/Roar.iconset"
mkdir -p "$ICONSET"

# Rasterise. Each entry is "size:filename"; the @2x variants share
# their pixel dimensions with the next-larger nominal size — that's
# the .iconset naming convention iconutil enforces (so 32x32 ships
# as both `icon_32x32.png` AND `icon_16x16@2x.png`, but the bytes
# are identical so we generate once and copy).
sizes=(
    "16:icon_16x16.png"
    "32:icon_16x16@2x.png"
    "32:icon_32x32.png"
    "64:icon_32x32@2x.png"
    "128:icon_128x128.png"
    "256:icon_128x128@2x.png"
    "256:icon_256x256.png"
    "512:icon_256x256@2x.png"
    "512:icon_512x512.png"
    "1024:icon_512x512@2x.png"
)

# Rasterise each size. macOS stock bash is 3.2 with no
# associative arrays, so this is the simple "rasterise every
# entry" loop — a few of them have identical pixel dimensions
# but rasterising 10x instead of 6x adds ~50ms, not worth the
# bash 4 dependency.
for entry in "${sizes[@]}"; do
    size="${entry%%:*}"
    name="${entry#*:}"
    rsvg-convert \
        --width "$size" \
        --height "$size" \
        --format png \
        --output "$ICONSET/$name" \
        "$SOURCE_SVG"
done

# Package the .iconset into the final .icns. `iconutil --convert
# icns` is the documented one-shot — it validates the .iconset
# layout, complains loudly if any required size is missing, and
# emits the binary container the bundle expects.
iconutil --convert icns --output "$OUTPUT_ICNS" "$ICONSET"

echo "wrote $OUTPUT_ICNS"
